name: 'Fork Sync'
description: 'Keep your fork up to date'
author: 'tgymnich'
branding:
  icon: 'git-branch'
  color: 'black'
inputs:
  owner:
    description: 'Owner of the forked repository'
    required: false
  token:
    description: 'Token for the github API'
    required: false
    default: ${{ github.token }}
  head:
    description: 'Branch to track'
    required: false
    default: 'master'
  base:
    description: 'Branch to keep updated'
    required: false
    default: 'master'
  merge_method:
    description: 'Merge method to use'
    required: false
    default: 'merge'
  pr_title:
    description: 'The title of the pull request'
    required: false
    default: 'Fork Sync: Update from parent repository'
  pr_message:
    description: 'The message in the pull request'
    required: false
  ignore_fail:
    description: 'Ignore Exceptions'
    required: false
    default: false
  auto_approve:
    description: 'Automatically approve pull request before merge'
    required: false
    default: false
  auto_merge:
    description: 'Automatically merge the pull request'
    required: false
    default: true
  retries:
    description: 'Retry count'
    required: false
    default: 4
  retry_after:
    description: 'Delay amount between retries'
    required: false
    default: 60

runs:
  using: 'node16'
  main: 'lib/main.js'
